### PR TITLE
Fix for Issue #50: Correct `meta.conversion` type in `EnrichedTransaction` model

### LINKED ISSUE #50: Inconsistency in `EnrichedTransaction` model - `meta.conversion` type
Hello,

I've noticed an inconsistency in the `EnrichedTransaction` model in the Akahu API. The `meta.conversion` field is currently typed as `string?` in the TypeScript definition, but the actual API response seems to return an object for this field.

Here's an example of the API response:

```json
"conversion": {
   "rate": 0.6098,
   "amount": 5,
   "currency": "USD"
}
```

This inconsistency is causing type errors when trying to access the properties of `meta.conversion` in TypeScript.

I understand that from #48 that some of the typings are out of date. 

Thank you for your attention to this matter.

### PR DESCRIPTION
**Pull request by nevercast**
Hello,

This pull request addresses the inconsistency noted in Issue #50. The `meta.conversion` field in the `EnrichedTransaction` model was incorrectly typed as `string?`. According to the API response, this field should be an object with `rate`, `amount`, and `currency` properties.

Changes made:

1. Introduced a new `Conversion` type to represent the conversion details of a transaction.
```typescript
type CurrencyConversion = {
  /**
   * The conversion rate used for the transaction.
   */
  rate: number,
  /**
   * The converted amount in the transaction.
   */
  amount: number,
  /**
   * The foreign currency in which the transaction was converted to/from.
   */
  currency: string
};
```

2. Updated the `EnrichedTransaction` type to use the `Conversion` type for the `meta.conversion` field.
```typescript
type EnrichedTransaction = RawTransaction & {
  // ...
  meta: {
    // ...
    conversion?: Conversion;
    // ...
  };
};
```

3. Updated the documentation, adding a `CurrencyConversion` section, and altering `EnrichedTransaction` to match the type changes.

Please review and let me know if any changes are required.

Fixes #50

Cheers

### CODE REVIEW

**Comment by dabrowne** [comment]
Hi @nevercast thanks for making this PR. Your improvements here are greatly appreciated.

The markdown docs are auto-generated (`npm run docs`), so you don't need to manually update them. However for that new `CurrencyConversion` type to come through it needs to be exported from the module. Can you please add an export for it in `models/index.ts`? You should then be able to see it in the documentation after running `npm run docs`.

**Comment by nevercast** [comment]
Hi @dabrowne,

Thank you for your feedback, I have made the following changes:
1. Rebased the first commit to remove the changes to README.md
2. Exported the CurrencyConversion type from `models/index.ts`
3. Tested `npm run docs` to ensure that the output is as expected.
4. Force Push to feature branch.

I hope this resolves any issues with the PR. 

Cheers

**Review by dabrowne — APPROVED** [review]

**Comment by dabrowne** [comment]
Published now in `akahu@1.15.3` thanks for your contribution @nevercast

**Comment by nevercast** [comment]
Wonderful! Thanks again for the fast turnaround @dabrowne! 🚀

**Pull request merged**
